[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
marinade_forking_smart_contract = "4ejpMtdY5cy9Gvqp5raVRLo5qQnz3UaDX9YSGUxewaa5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=f74ec75c-56ba-49df-b67b-71637bf8d115"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
