[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.25"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solistic_staking = "sStz8DdEKCeB5kiNcU634MWvxgPuikAxcE5YnNBsmc4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com "
wallet = "./id.json"

[workspace]
members = ["programs/solistic-staking"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
