[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.25"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
solistic_staking = "SStKUUWsgH8Ed1eXqN96tcwhLnAVQ5jtui3wkWcxqHL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=xxxx"
# cluster = "https://api.devnet.solana.com"
wallet = "<path>"

[workspace]
members = ["programs/solistic-staking"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"