[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.25"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solistic_staking = "Sstkf2jUrQsoZ2Co1VwMksEyEqPTcQgxyiatpLrn74n"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://mainnet.helius-rpc.com/?api-key=45889935-3d12-491a-b220-3cc87211f3d6"
cluster = "https://api.devnet.solana.com"
wallet = "/home/ubuntu/solistic/solistic-mainnet/.keys/AdMkcNdPXBKMofRFN71v6tyJtzdQ2s3x5Snv6DKk3GS2.json"

[workspace]
members = ["programs/solistic-staking"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"