[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.25"

[features]
resolution = true
skip-lint = false

[programs.devnet]
marinade_forking_smart_contract = "2PpfLxCrrwb3Eb9pn3uC2FyWWqK6mH7RQDNy9hgF2pTW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com "
wallet = "./id.json"

[workspace]
members = ["programs/marinade-forking-smart-contract"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
