[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.17.34" # Solana version to use

[features]
resolution = true
skip-lint = false

[programs.localnet]
solistic_liquid_staking = "E42rv7jcez9BhqBDHxG8WaMw9PvHEToVCMrHUXbHghVN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
